# Generated by Django 6.0 on 2026-02-18 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
