# Generated by Django 6.0 on 2026-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
