# Generated by Django 6.0 on 2026-03-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_host'),
        ('base', '0013_chat_chatmessage_chattheme_chat_theme_and_more'),
    ]

    operations = [
    ]
