# Generated by Django 6.0 on 2026-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_studyresource_studyplan_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
