# Generated by Django 6.0 on 2026-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_studyplan_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
    ]
